### ISSUE TITLE
can I limit data to geo lat and long coordinates?

### ISSUE THREAD

**Issue by alisoleimanii** [RezaParsian/Balad#1]
Hi there.
I like this repo and what`s it does but I have a question :)
Can I give the app geo coordinates of an area and say to it just crawl this area?

**Comment by RezaParsian** [comment]
Hi :D.

yeah you can do that with polygon coordination something like link below.

https://search.raah.ir/v4/bundle-search/?slug=cng-station&polygon=50.7835523156827%2C34.675747835395725%7C50.96660886659714%2C34.675747835395725%7C50.96660886659714%2C34.61967142840432%7C50.7835523156827%2C34.61967142840432%7C50.7835523156827%2C34.675747835395725&camera=50.87508059113992%2C34.64770963190002

this repository made for my [YouTube](https://youtu.be/5VRT1PvNrp0) tutorial.
